name: Employee Management CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
      - name: Verify Application
        run: |
          cd app
          python app.py &
          sleep 5
          curl http://127.0.0.1:5000/health
      - name: Build Docker Image
        run: |
          docker build -t employee-management:${{ github.sha }} .
      - name: Login to Docker Hub
        uses: docker/login-action@184bdaa094e800f96e35e82c6b7e1f8a6e3a6e3a   
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.ACCESS_TOKEN }}
      - name: Push Docker Image
        run: |
          docker tag employee-management:${{ github.sha }} ramanjaneyalup8/employee-management:${{ github.sha }}
          docker push ramanjaneyalup8/employee-management:${{ github.sha }}



