name: Employee Management CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop #this triggers workflow when PR is raised to develop branch 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
      - name: Verify Application
        run: |
          cd app
          python app.py &
          sleep 5
          curl http://127.0.0.1:5000/health
      - name: Build Docker Image
        run: |
          docker build \
            -t employee-management:${{ github.sha }} \
            -t employee-management:latest .
      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.ACCESS_TOKEN }}
      - name: Push Docker Image
        if: github.event_name == 'push'
        run: |
          docker tag employee-management:${{ github.sha }} ramanjaneyalup8/employee-management:${{ github.sha }}
          docker tag employee-management:latest ramanjaneyalup8/employee-management:latest

          docker push ramanjaneyalup8/employee-management:${{ github.sha }}
          docker push ramanjaneyalup8/employee-management:latest


  deploy:
    name: Deploy to EC2

    needs: build

    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

    steps:

      - name: Checkout Repositor
        uses: actions/checkout@v4
      - name: Debug GitHub Context
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Git Ref: ${{ github.ref }}"
          echo "Ref Name: ${{ github.ref_name }}"
          echo "SHA: ${{ github.sha }}"

      - name: Copy deploy.sh to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_ADDRESS }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY_PEM }}
          source: "scripts/deploy.sh"
          target: "/home/ubuntu/deployment"

      - name: Execute deployment script on EC2
        uses: appleboy/ssh-action@v1.2.0


        with:
          host: ${{ secrets.EC2_HOST_ADDRESS }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY_PEM }}

          script: |
            chmod +x /home/ubuntu/deployment/scripts/deploy.sh

            echo "Starting deployment..."

            /home/ubuntu/deployment/scripts/deploy.sh \
            ramanjaneyalup8/employee-management:${{ github.sha }} \
            employee-management

